spring:
  application:
    name: god-a-rede-app-auth-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}

security:
  jwt:
    expiration: 300
    issuer: http://${APP_HOSTNAME:localhost}:${server.port}
server:
  port: 8081


